services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CurtinHonestly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./curtin-honestly-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=CurtinHonestly
    depends_on:
      - db

  frontend:
    build: ./angular-workspace
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
